export const FRONTEND_DATA = [
  {
    title: "Javascript",
    description: "The fundamentals",
    date: "Feb. 2022",
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    avatar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
  },
  {
    title: "Typescript",
    description: "Prevent errors before they happen",
    date: "Jan. 2023",
    url: "https://www.typescriptlang.org/",
    avatar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
  },
  {
    title: "React",
    description: "Most popular framework for a reason",
    date: "Mar. 2022",
    url: "https://react.dev/",
    avatar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
  },
  {
    title: "Redux Toolkit",
    description: "Most popular state management library",
    date: "Mar. 2023",
    url: "https://redux-toolkit.js.org/",
    avatar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg",
  },
  {
    title: "Jotai",
    description: "Lightweight state management library",
    date: "Apr. 2023",
    url: "https://jotai.org/",
    avatar: "/jotai.png",
  },
  {
    title: "Next.js",
    description: "React on steroids",
    date: "Apr. 2023",
    url: "https://nextjs.org/",
    avatar: "/nextjs.png",
  },
  {
    title: "Jest",
    description: " Front-end unit testing",
    date: "Mar. 2023",
    url: "https://jestjs.io/",
    avatar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jest/jest-plain.svg",
  },
  {
    title: "React Router",
    description: "Vanilla page routing for React",
    date: "Mar. 2022",
    url: "https://reactrouter.com/en/main",
    avatar: "/reactrouter.png",
  },

  {
    title: "Chart.js",
    description: "Charting library of choice",
    date: "Apr. 2023",
    url: "https://www.chartjs.org/",
    avatar: "/chartjs.png",
  },
  {
    title: "React-Leaflet",
    description: "Mapping library of choice",
    date: "Apr. 2023",
    url: "https://react-leaflet.js.org/",
    avatar: "/reactleaflet.png",
  },
]

export const BACKEND_DATA = [
  {
    title: "Node.js",
    description: "Backend language of choice",
    date: "Dec. 2022",
    url: "https://nodejs.org/en",
    avatar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
  },
  {
    title: "Express",
    description: "Framework library for Node",
    date: "Dec. 2022",
    url: "https://expressjs.com/",
    avatar: "/express.png",
  },
  {
    title: "MongoDB",
    description: "Database of choice",
    date: "Dec. 2022",
    url: "https://www.mongodb.com/",
    avatar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
  },
  {
    title: "MySQL",
    description: "The classic DB",
    date: "Feb. 2023",
    url: "https://www.mysql.com/",
    avatar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg",
  },
  {
    title: "Git",
    description: "Version control",
    date: "Jan. 2023",
    url: "https://git-scm.com/",
    avatar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg",
  },
  {
    title: "Vite",
    description: "Create-React-App but it's 2023",
    date: "Mar. 2022",
    url: "https://vitejs.dev/",
    avatar: "/vite.png",
  },
]

export const STYLING_DATA = [
  {
    title: "CSS",
    description: "The fundamentals",
    date: "Jan. 2022",
    url: "https://developer.mozilla.org/en-US/docs/Web/CSS",
    avatar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg",
  },
  {
    title: "TailwindCSS",
    description: "Framework of choice",
    date: "Dec. 2022",
    url: "https://tailwindcss.com/",
    avatar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-plain.svg",
  },
  {
    title: "SASS",
    description: "Not as cool as Tailwind",
    date: "Jun. 2022",
    url: "https://sass-lang.com/",
    avatar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg",
  },
  {
    title: "Figma",
    description: "Design tool of choice",
    date: "Mar. 2023",
    url: "https://www.figma.com/",
    avatar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg",
  },
  {
    title: "Framer Motion",
    description: "Animation library of choice",
    date: "Feb. 2023",
    url: "https://www.framer.com/motion/",
    avatar: "/framer.webp",
  },
  {
    title: "shadcn/UI",
    description: "Component library of choice",
    date: "Mar. 2023",
    url: "https://ui.shadcn.com/",
    avatar: "/shadcn.webp",
  },
  {
    title: "Radix UI",
    description: "My choice before discovering shadcn",
    date: "Jan. 2023",
    url: "https://www.radix-ui.com/",
    avatar: "/radixUI.png",
  },
  {
    title: "Bootstrap",
    description: "Most popular component library for a reason",
    date: "Mar. 2023",
    url: "https://getbootstrap.com/",
    avatar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg",
  },
  {
    title: "MaterialUI",
    description: "Second most popular component library for a reason",
    date: "Mar. 2023",
    url: "https://mui.com/",
    avatar: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/materialui/materialui-original.svg",
  },
]
