export const SKILLS = [
  {
    name: "React",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
    category: "fundamental",
    url: "https://react.dev/",
  },
  {
    name: "Redux Toolkit",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg",
    category: "familiarity",
    url: "https://redux-toolkit.js.org/",
  },
  {
    name: "Javascript",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
    category: "fundamental",
  },
  {
    name: "TypeScript",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
    category: "fundamental",
    url: "https://www.typescriptlang.org/",
  },
  {
    name: "Next.js",
    icon: "/nextjs.png",
    category: "familiarity",
    url: "https://nextjs.org/",
  },
  {
    name: "Git",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg",
    category: "fundamental",
    url: "https://git-scm.com/",
  },
  {
    name: "HTML",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg",
    category: "fundamental",
  },
  {
    name: "CSS",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg",
    category: "fundamental",
  },

  {
    name: "Node.js",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
    category: "familiarity",
    url: "https://nodejs.org/en",
  },
  {
    name: "Express",
    icon: "/express.png",
    category: "familiarity",
    url: "https://expressjs.com/",
  },
  {
    name: "MongoDB",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
    category: "familiarity",
    url: "https://www.mongodb.com/",
  },
  {
    name: "MySQL",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg",
    category: "beginner",
    url: "https://www.mysql.com/",
  },
  {
    name: "Jotai",
    icon: "/jotai.png",
    category: "fundamental",
    url: "https://jotai.org/",
  },
  {
    name: "React Router",
    icon: "/reactrouter.png",
    category: "familiarity",
    url: "https://reactrouter.com/en/main",
  },
  {
    name: "Vite",
    icon: "/vite.png",
    category: "familiarity",
    url: "https://vitejs.dev/",
  },
  {
    name: "Figma",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg",
    category: "beginner",
    url: "https://www.figma.com/",
  },
  {
    name: "Jest",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jest/jest-plain.svg",
    category: "beginner",
    url: "https://jestjs.io/",
  },
  {
    name: "SASS",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg",
    category: "familiarity",
    url: "https://sass-lang.com/",
  },
  {
    name: "TailwindCSS",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-plain.svg",
    category: "fundamental",
    url: "https://tailwindcss.com/",
  },
  {
    name: "Bootstrap",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg",
    category: "familiarity",
    url: "https://getbootstrap.com/",
  },
  {
    name: "MaterialUI",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/materialui/materialui-original.svg",
    category: "familiarity",
    url: "https://mui.com/",
  },
  {
    name: "Framer Motion",
    icon: "/framer.webp",
    category: "familiarity",
    url: "https://www.framer.com/motion/",
  },
  {
    name: "RadixUI",
    icon: "/radixUI.png",
    category: "familiarity",
    url: "https://www.radix-ui.com/",
  },
  {
    name: "Chart.js",
    icon: "/chartjs.png",
    category: "beginner",
    url: "https://www.chartjs.org/",
  },
]
